/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BBoardIndexRouteImport } from './routes/b/$board/index'
import { Route as BBoardTTopicRouteImport } from './routes/b/$board/t.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BBoardIndexRoute = BBoardIndexRouteImport.update({
  id: '/b/$board/',
  path: '/b/$board/',
  getParentRoute: () => rootRouteImport,
} as any)
const BBoardTTopicRoute = BBoardTTopicRouteImport.update({
  id: '/b/$board/t/$topic',
  path: '/b/$board/t/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/b/$board': typeof BBoardIndexRoute
  '/b/$board/t/$topic': typeof BBoardTTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/b/$board': typeof BBoardIndexRoute
  '/b/$board/t/$topic': typeof BBoardTTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/b/$board/': typeof BBoardIndexRoute
  '/b/$board/t/$topic': typeof BBoardTTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/b/$board' | '/b/$board/t/$topic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/b/$board' | '/b/$board/t/$topic'
  id: '__root__' | '/' | '/b/$board/' | '/b/$board/t/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BBoardIndexRoute: typeof BBoardIndexRoute
  BBoardTTopicRoute: typeof BBoardTTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$board/': {
      id: '/b/$board/'
      path: '/b/$board'
      fullPath: '/b/$board'
      preLoaderRoute: typeof BBoardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$board/t/$topic': {
      id: '/b/$board/t/$topic'
      path: '/b/$board/t/$topic'
      fullPath: '/b/$board/t/$topic'
      preLoaderRoute: typeof BBoardTTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BBoardIndexRoute: BBoardIndexRoute,
  BBoardTTopicRoute: BBoardTTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
